SS17 Final Code Changes
Roboy/Vision pull request #21
Opened 2017-08-30 21:44 UTC by byteofprash

1. All the code part of the Final presentation is pushed. 
2. Doxygen comments for the modules added
3. Documentation updated.
4. ROS messages updated, with description. 
5. RosMsgUtil template with Services and msgs implemented. 

**setup.sh** script will install all the dependencies for

2017-08-30 21:49 UTC, missxa commented
o_O

2017-08-30 21:51 UTC, byteofprash commented
Yes? Is something missing?

2017-08-30 21:52 UTC, missxa commented
lol, what's happening?
not, it's just huge

2017-09-02 17:21 UTC, missxa requested changes
Since Github webview lags due to insane amount of files changed in this PR (probably): here's docs review summary 
1. Update index.rst, add what are current capabilities of the Vision module
2.  Update getting started to include how to run it and use your module
3.  Move architecture diagram from solution strategy into a separate chapter
4. Add a link from "getting started" to public interfaces. rename it to Public Interfaces (ROS)
5. Add API section: has to show your in-code comments (i don't understand why you didn't do it yet, since the comments are there). here is what i mean http://roboy-memory.readthedocs.io/en/develop/ScopeContext/9_API.html

Files in repo:
- remove .idea folder
- or any __pycache__ folders you pushed to the repo
- remove .catkin_workspace
- update your .gitignore to avoid this kind of things in the future

As I can see, ROS functionality is there but is not currently used. We'll work on it starting next semester then. Please address the comments so we do a release asap

2017-09-02 17:21 UTC, missxa commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
remove .idea folder

2017-09-02 17:21 UTC, missxa commented on src/vision_service/srv/DescribeScene.srv
> +---
src/vision_service is not needed. remove the folder and mention in the docs, that roboy_communication_cognition is required

2017-09-02 17:21 UTC, missxa commented on src/zed/zedRoboy.py
> +from ctypes import *
what is it? we are planning to use the ZED official python wrapper. seems like zed-related cpp/hpp files are obsolete. delete unnecessary or explain the need

2017-09-02 17:21 UTC, missxa commented on src/ObjectRecognition.py
> +"""@package RecogniseFace
typo

2017-09-02 17:21 UTC, missxa commented on src/RecogniseFace.py
> +"""@package RecogniseFace
typo

2017-09-02 17:21 UTC, missxa commented on src/RecogniseFace.py
> +        prashFace = [-0.00111124,  0.05805413,  0.02128297,  0.03982484,  0.12203307,
store features in a separate file and load them (pickle/json)

2017-09-02 17:21 UTC, missxa commented on src/RecogniseFace.py
> +           # train(session)
clean up comments

2017-09-02 17:21 UTC, missxa commented on src/RosMsgUtil.py
> +def AdvertiseNewFacialFeatures():
duplicated functionality with NewFacialFeatures.msg

2017-09-02 17:21 UTC, missxa commented on src/RosMsgUtil.py
> +def AdvertiseDescribeScene():
duplicated functionality with DescribeSceneSrv.py

2017-09-02 17:21 UTC, missxa commented on src/RosMsgUtil.py
> +2. The send functions here are called from different modules.
could not find RosMsgUtil function calls in other modules

2017-09-02 17:21 UTC, missxa commented on src/RosMsgUtil.py
> +def AdvertiseContinously():
does not need to be continuous, just once
+typo in name

2017-09-20 13:49 UTC, byteofprash commented
@missxa Could we proceed with the merging into master? Is something else pending apart from the API docs?

2017-09-24 14:12 UTC, missxa approved these changes

2017-09-24 14:13 UTC, merged